# Only [allowlist] is picked up by the LeakTK scanning service
[allowlist]
  description = "Repo Allowlist"
  paths = [
    'modules/custom-cert-new-install.adoc',
    'modules/custom-cert-existing.adoc',
    
    # Some test ignores for working with the scanner's unit tests
    '''ignore\.d''',
    '''\.ignore\.txt$''',

    # Ignore the .gitleaks.toml
    '''\.gitleaks\.toml$''',
  ]
  regexes = [
    # '''custom-regexes-to-ignore-here''',
  ]

# [[rules]] are not picked up by the LeakTK scanning service
[[rules]]
  description = "fake-leaks-custom-rule"
  regex = '''asdfasdfasdfasdf'''
  tags = ["fake-leaks-custom-rule"]